/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-10-28 06:11:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Index;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Header</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Index.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"HeaderRes.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- \r\n");
      out.write("        Create: Cao Thành Nam\r\n");
      out.write("        Date: 18/10/2023\r\n");
      out.write("        Note: header của trang web \r\n");
      out.write("    -->\r\n");
      out.write("	<div class=\"header\">\r\n");
      out.write("		<img src=\"/asset/image/general/logo.png\" alt=\"\" class=\"logo_page\">\r\n");
      out.write("\r\n");
      out.write("		<!-- phần tìm kiếm sản phẩm của header -->\r\n");
      out.write("		<div class=\"header_search\">\r\n");
      out.write("			<input type=\"text\" class=\"search\" placeholder=\"Tìm đồ gia dụng\">\r\n");
      out.write("			<i class=\"fa-solid fa-magnifying-glass search_logo\"></i>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- phần đăng nhập hoặc đăng ký của header -->\r\n");
      out.write("		<div class=\"header_login_signin\">\r\n");
      out.write("			<a href=\"/asset/html/login.html\" class=\"log_in\">Đăng nhập</a>\r\n");
      out.write("			<div class=\"line\"></div>\r\n");
      out.write("			<a href=\"/asset//html/register.html\" class=\"sign_in\">Đăng ký</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"header_login_signin_mobile\">\r\n");
      out.write("			<img src=\"/asset/image/png/user.png\" alt=\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- phần giỏ hàng của header -->\r\n");
      out.write("		<div class=\"header_cart\">\r\n");
      out.write("			<div class=\"header_cart_info\">\r\n");
      out.write("				<img src=\"/asset/image/png/cart.png\" class=\"header_cart_logo\" alt=\"\">\r\n");
      out.write("				<span class=\"header_cart_amount_product\">0</span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- phần danh mục sản phẩm của header -->\r\n");
      out.write("	<div class=\"navigation\">\r\n");
      out.write("		<div class=\"all_list\">\r\n");
      out.write("			<i class=\"fa-solid fa-list all_list_logo\"></i> <span\r\n");
      out.write("				class=\"all_list_text\">Tất cả danh mục</span>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<ul class=\"navigtion-list\">\r\n");
      out.write("			<li class=\"navigtion-item\"><a href=\"\">Tivi</a></li>\r\n");
      out.write("			<li class=\"navigtion-item\"><a href=\"\">Máy giặt</a></li>\r\n");
      out.write("			<li class=\"navigtion-item\"><a href=\"\">Tủ lạnh</a></li>\r\n");
      out.write("			<li class=\"navigtion-item\"><a href=\"\">Máy sấy</a></li>\r\n");
      out.write("			<li class=\"navigtion-item\"><a href=\"\">Gia dụng</a></li>\r\n");
      out.write("			<li class=\"navigtion-item\"><a href=\"\">Robot hút bụi</a></li>\r\n");
      out.write("			<li class=\"navigtion-item\"><a href=\"\">Bếp điện</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"modal_overlay\"></div>\r\n");
      out.write("	<div class=\"modal_body\">\r\n");
      out.write("		<i class=\"fa-solid fa-xmark modal_body_quit\"></i>\r\n");
      out.write("		<ul class=\"category_all_list\">\r\n");
      out.write("			<div>\r\n");
      out.write("				<li class=\"category_all_item\">Sofa và Armchair <i\r\n");
      out.write("					class=\"fa-solid fa-chevron-down category_all_item_icon\"></i>\r\n");
      out.write("				</li>\r\n");
      out.write("				<ul class=\"category_all_item_child_list\">\r\n");
      out.write("					<li>Sofa</li>\r\n");
      out.write("					<li>Sofa góc</li>\r\n");
      out.write("					<li>Ghế dài và đôn</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div>\r\n");
      out.write("				<li class=\"category_all_item\">Bàn <i\r\n");
      out.write("					class=\"fa-solid fa-chevron-down category_all_item_icon\"></i>\r\n");
      out.write("				</li>\r\n");
      out.write("				<ul class=\"category_all_item_child_list\">\r\n");
      out.write("					<li>Sofa</li>\r\n");
      out.write("					<li>Sofa góc</li>\r\n");
      out.write("					<li>Ghế dài và đôn</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div>\r\n");
      out.write("				<li class=\"category_all_item\">Ghế <i\r\n");
      out.write("					class=\"fa-solid fa-chevron-down category_all_item_icon\"></i>\r\n");
      out.write("				</li>\r\n");
      out.write("				<ul class=\"category_all_item_child_list\">\r\n");
      out.write("					<li>Sofa</li>\r\n");
      out.write("					<li>Sofa góc</li>\r\n");
      out.write("					<li>Ghế dài và đôn</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div>\r\n");
      out.write("				<li class=\"category_all_item\">Giường ngủ <i\r\n");
      out.write("					class=\"fa-solid fa-chevron-down category_all_item_icon\"></i>\r\n");
      out.write("				</li>\r\n");
      out.write("				<ul class=\"category_all_item_child_list\">\r\n");
      out.write("					<li>Sofa</li>\r\n");
      out.write("					<li>Sofa góc</li>\r\n");
      out.write("					<li>Ghế dài và đôn</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div>\r\n");
      out.write("				<li class=\"category_all_item\">Tủ và kệ <i\r\n");
      out.write("					class=\"fa-solid fa-chevron-down category_all_item_icon\"></i></li>\r\n");
      out.write("				<ul class=\"category_all_item_child_list\">\r\n");
      out.write("					<li>Sofa</li>\r\n");
      out.write("					<li>Sofa góc</li>\r\n");
      out.write("					<li>Ghế dài và đôn</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.js\"\r\n");
      out.write("	integrity=\"sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("	var elementModal = document.querySelector('.modal_overlay');\r\n");
      out.write("	var elementModalBody = document.querySelector('.modal_body');\r\n");
      out.write("	var elementIconAllList = document.querySelector('.all_list');\r\n");
      out.write("	var elementQuitIcon = document.querySelector(\".modal_body_quit\");\r\n");
      out.write("	var elementBody = document.querySelector('body');\r\n");
      out.write("\r\n");
      out.write("	/*\r\n");
      out.write("	 Create: Cao Thành Nam\r\n");
      out.write("	 Date: 22/10/2023\r\n");
      out.write("	 Note: phương thức xử lý bắt đầu ấn vào tất cả danh mục\r\n");
      out.write("	 */\r\n");
      out.write("\r\n");
      out.write("	function _startSlideAllList() {\r\n");
      out.write("		elementIconAllList.onclick = function() {\r\n");
      out.write("			_slideLeftToRightAllList();\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/*\r\n");
      out.write("	 Create: Cao Thành Nam\r\n");
      out.write("	 Date: 22/10/2023\r\n");
      out.write("	 Note: phương thức css cho các modal để hiển thị lên màn hình\r\n");
      out.write("	 */\r\n");
      out.write("\r\n");
      out.write("	function _slideLeftToRightAllList() {\r\n");
      out.write("		elementModal.classList.toggle(\"active\")\r\n");
      out.write("		elementModalBody.style.left = '0';\r\n");
      out.write("		elementBody.classList.add('hidden_overflow');\r\n");
      out.write("	}\r\n");
      out.write("	/*\r\n");
      out.write("	 Create: Cao Thành Nam\r\n");
      out.write("	 Date: 22/10/2023\r\n");
      out.write("	 Note: phương thức xử lý khi băt đầu ấn vào tắt danh mục,\r\n");
      out.write("	 ấn vào nút X hoặc nhấn ra ngoài danh mục\r\n");
      out.write("	 */\r\n");
      out.write("	function _clickQuit() {\r\n");
      out.write("		elementQuitIcon.onclick = function() {\r\n");
      out.write("			_quitSlide();\r\n");
      out.write("		}\r\n");
      out.write("		elementModal.onclick = function() {\r\n");
      out.write("			_quitSlide();\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/*\r\n");
      out.write("	 Create: Cao Thành Nam\r\n");
      out.write("	 Date: 22/10/2023\r\n");
      out.write("	 Note: phương thức xử lý để modal tắt khỏi màn hình\r\n");
      out.write("	 */\r\n");
      out.write("	function _quitSlide() {\r\n");
      out.write("		elementModal.classList.remove(\"active\")\r\n");
      out.write("		elementModalBody.style.left = -$(elementModalBody).width() + \"px\";\r\n");
      out.write("		elementBody.classList.remove('hidden_overflow');\r\n");
      out.write("\r\n");
      out.write("		setTimeout(function() {\r\n");
      out.write("			elementCategoryItem.forEach(function(value, index) {\r\n");
      out.write("				_resetSlide(index);\r\n");
      out.write("			})\r\n");
      out.write("		}, 350);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	var elementCategoryItem = document.querySelectorAll(\".category_all_item\");\r\n");
      out.write("	var elementCategoryChildItem = document\r\n");
      out.write("			.querySelectorAll(\".category_all_item_child_list\");\r\n");
      out.write("	var elementIconDown = document.querySelectorAll(\".category_all_item_icon\");\r\n");
      out.write("\r\n");
      out.write("	/*\r\n");
      out.write("	 Create: Cao Thành Nam\r\n");
      out.write("	 Date: 22/10/2023\r\n");
      out.write("	 Note: phương thức reset lại modal trở về vị trí ban đầu\r\n");
      out.write("	 */\r\n");
      out.write("	function _resetSlide(index) {\r\n");
      out.write("		elementCategoryChildItem[index].classList.replace('active', 'unactive');\r\n");
      out.write("		elementIconDown[index].classList.replace('icon_up_rotate',\r\n");
      out.write("				'icon_down_rotate');\r\n");
      out.write("		elementCategoryItem[index].classList\r\n");
      out.write("				.remove('category_all_item_border-none');\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/*\r\n");
      out.write("	 Create: Cao Thành Nam\r\n");
      out.write("	 Date: 22/10/2023\r\n");
      out.write("	 Note: phương thức xử lý khi ấn vào từng item sẽ hiện lên item con\r\n");
      out.write("	 */\r\n");
      out.write("	function _clickChildItem() {\r\n");
      out.write("		elementCategoryItem.forEach(function(value, index) {\r\n");
      out.write("			value.onclick = function() {\r\n");
      out.write("				value.classList.toggle(\"category_all_item_border-none\");\r\n");
      out.write("				elementCategoryChildItem[index].classList.toggle('active');\r\n");
      out.write("				elementIconDown[index].classList.toggle('icon_up_rotate');\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	_startSlideAllList();\r\n");
      out.write("	_clickQuit();\r\n");
      out.write("	_clickChildItem();\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
