/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-10-28 06:13:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Index;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Index.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("	<!-- \r\n");
      out.write("            Create: Cao Thành Nam\r\n");
      out.write("            Date: 18/10/2023\r\n");
      out.write("            Note: phần body của trang\r\n");
      out.write("        -->\r\n");
      out.write("	<div class=\"slider container\">\r\n");
      out.write("		<div class=\"slider_img_list\">\r\n");
      out.write("			<img class=\"slider_img_item\"\r\n");
      out.write("				src=\"asset/image/jpg/content_introduce.jpg\" alt=\"\"> <img\r\n");
      out.write("				class=\"slider_img_item\" src=\"asset/image/png/content_introduce1.png\"\r\n");
      out.write("				alt=\"\"> <img class=\"slider_img_item\"\r\n");
      out.write("				src=\"asset/image/jpg/content_introduce.jpg\" alt=\"\"> <img\r\n");
      out.write("				class=\"slider_img_item\" src=\"asset/image/jpg/content_introduce.jpg\"\r\n");
      out.write("				alt=\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"slider_dot_list\">\r\n");
      out.write("			<div class=\"slider_dot_item background_dot_slider-active\"></div>\r\n");
      out.write("			<div class=\"slider_dot_item\"></div>\r\n");
      out.write("			<div class=\"slider_dot_item\"></div>\r\n");
      out.write("			<div class=\"slider_dot_item\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<i class=\"fa-solid fa-angle-left left\"></i> <i\r\n");
      out.write("			class=\"fa-solid fa-angle-right right\"></i>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"content\">\r\n");
      out.write("		<div class=\"content_event_product container\">\r\n");
      out.write("			<div class=\"product_event\">\r\n");
      out.write("				<img src=\"asset/image/png/img_event_1.png\" alt=\"\">\r\n");
      out.write("				<p>Cao Cấp Bao giá freeship</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product_event\">\r\n");
      out.write("				<img src=\"asset/image/png/img_event_2.png\" alt=\"\">\r\n");
      out.write("				<p>Tivi trưng bày giảm đến 100%</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product_event\">\r\n");
      out.write("				<img src=\"asset/image/png/img_event_3.png\" alt=\"\">\r\n");
      out.write("				<p>Máy xay sinh tố 1x.xxx</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product_event\">\r\n");
      out.write("				<img src=\"asset/image/png/img_event_4.png\" alt=\"\">\r\n");
      out.write("				<p>Bếp điện đôi từ 1.xxx</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container introduce_product\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-6 introduce_product_item\">\r\n");
      out.write("					<img src=\"asset/image/jpg/introduce_product.jpg\" alt=\"\">\r\n");
      out.write("					<h3 class=\"introduce_product_name\">Quạt</h3>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-6\">\r\n");
      out.write("					<div class=\"row\" style=\"padding-bottom: 15px;\">\r\n");
      out.write("						<div class=\"col-lg-6 introduce_product_item\">\r\n");
      out.write("							<img src=\"asset/image/jpg/introduce_product.jpg\" alt=\"\">\r\n");
      out.write("							<h3 class=\"introduce_product_name\">Tivi</h3>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-6 introduce_product_item\">\r\n");
      out.write("							<img src=\"asset/image/jpg/introduce_product.jpg\" alt=\"\">\r\n");
      out.write("							<h3 class=\"introduce_product_name\">Tủ lạnh</h3>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row\" style=\"padding-top: 14px;\">\r\n");
      out.write("						<div class=\"col-lg-6 introduce_product_item\">\r\n");
      out.write("							<img src=\"asset/image/jpg/introduce_product.jpg\" alt=\"\">\r\n");
      out.write("							<h3 class=\"introduce_product_name\">Bàn ăn</h3>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-6 introduce_product_item\">\r\n");
      out.write("							<img src=\"asset/image/jpg/introduce_product.jpg\" alt=\"\">\r\n");
      out.write("							<h3 class=\"introduce_product_name\">Ghế ngồi</h3>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"product_list container\">\r\n");
      out.write("			<h2 style=\"margin-bottom: 20px; cursor: default;\">\r\n");
      out.write("				Sản phẩm nổi bật\r\n");
      out.write("				</h1>\r\n");
      out.write("				<div class=\"row mb-3\">\r\n");
      out.write("					<div class=\"col-lg-3 col-sm-6 col-md-4 product\">\r\n");
      out.write("						<div class=\"product_img\">\r\n");
      out.write("							<img src=\"asset/image/jpg/product_img.jpg\" alt=\"\">\r\n");
      out.write("							<div class=\"product_img_hover\">\r\n");
      out.write("								<img src=\"asset/image/jpg/product_img_hover.jpg\" alt=\"\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product_in4\">\r\n");
      out.write("							<p class=\"product_in4_name_product\">ngoi cao cap sieu vip pro\r\n");
      out.write("								vu tru</p>\r\n");
      out.write("							<div class=\"product_in4_bottom\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<p class=\"product_in4_price\">12,000,000₫</p>\r\n");
      out.write("									<p class=\"product_in4_sale_price\">6,000,000₫</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"product_in4_wishlist\">\r\n");
      out.write("									<i class=\"fa-solid fa-heart\"></i> <span class=\"hint_wishlist\">yêu\r\n");
      out.write("										thích</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"product_btn\">\r\n");
      out.write("							<a class=\" product_btn-add_card_none\">Thêm vào giỏ</a> <a\r\n");
      out.write("								class=\" product_btn--product_detail_none\">xem thêm</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-3 col-sm-6 col-md-4 product\">\r\n");
      out.write("						<div class=\"product_img\">\r\n");
      out.write("							<img src=\"asset/image/jpg/product_img.jpg\" alt=\"\">\r\n");
      out.write("							<div class=\"product_img_hover\">\r\n");
      out.write("								<img src=\"asset/image/jpg/product_img_hover.jpg\" alt=\"\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product_in4\">\r\n");
      out.write("							<p class=\"product_in4_name_product\">ngoi cao cap sieu vip pro\r\n");
      out.write("								vu tru</p>\r\n");
      out.write("							<div class=\"product_in4_bottom\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<p class=\"product_in4_price\">12,000,000₫</p>\r\n");
      out.write("									<p class=\"product_in4_sale_price\">6,000,000₫</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"product_in4_wishlist\">\r\n");
      out.write("									<i class=\"fa-solid fa-heart\"></i> <span class=\"hint_wishlist\">yêu\r\n");
      out.write("										thích</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"product_btn\">\r\n");
      out.write("							<a class=\" product_btn-add_card_none\">Thêm vào giỏ</a> <a\r\n");
      out.write("								class=\" product_btn--product_detail_none\">xem thêm</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-3 col-sm-6 col-md-4 product\">\r\n");
      out.write("						<div class=\"product_img\">\r\n");
      out.write("							<img src=\"asset/image/jpg/product_img.jpg\" alt=\"\">\r\n");
      out.write("							<div class=\"product_img_hover\">\r\n");
      out.write("								<img src=\"asset/image/jpg/product_img_hover.jpg\" alt=\"\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product_in4\">\r\n");
      out.write("							<p class=\"product_in4_name_product\">ngoi cao cap sieu vip pro\r\n");
      out.write("								vu tru</p>\r\n");
      out.write("							<div class=\"product_in4_bottom\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<p class=\"product_in4_price\">12,000,000₫</p>\r\n");
      out.write("									<p class=\"product_in4_sale_price\">6,000,000₫</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"product_in4_wishlist\">\r\n");
      out.write("									<i class=\"fa-solid fa-heart\"></i> <span class=\"hint_wishlist\">yêu\r\n");
      out.write("										thích</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"product_btn\">\r\n");
      out.write("							<a class=\" product_btn-add_card_none\">Thêm vào giỏ</a> <a\r\n");
      out.write("								class=\" product_btn--product_detail_none\">xem thêm</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-3 col-sm-6 col-md-4 product\">\r\n");
      out.write("						<div class=\"product_img\">\r\n");
      out.write("							<img src=\"asset/image/jpg/product_img.jpg\" alt=\"\">\r\n");
      out.write("							<div class=\"product_img_hover\">\r\n");
      out.write("								<img src=\"asset/image/jpg/product_img_hover.jpg\" alt=\"\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product_in4\">\r\n");
      out.write("							<p class=\"product_in4_name_product\">ngoi cao cap sieu vip pro\r\n");
      out.write("								vu tru</p>\r\n");
      out.write("							<div class=\"product_in4_bottom\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<p class=\"product_in4_price\">12,000,000₫</p>\r\n");
      out.write("									<p class=\"product_in4_sale_price\">6,000,000₫</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"product_in4_wishlist\">\r\n");
      out.write("									<i class=\"fa-solid fa-heart\"></i> <span class=\"hint_wishlist\">yêu\r\n");
      out.write("										thích</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"product_btn\">\r\n");
      out.write("							<a class=\" product_btn-add_card_none\">Thêm vào giỏ</a> <a\r\n");
      out.write("								class=\" product_btn--product_detail_none\">xem thêm</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"row mb-3\">\r\n");
      out.write("					<div class=\"col-lg-3 col-sm-6 col-md-4 product\">\r\n");
      out.write("						<div class=\"product_img\">\r\n");
      out.write("							<img src=\"asset/image/jpg/product_img.jpg\" alt=\"\">\r\n");
      out.write("							<div class=\"product_img_hover\">\r\n");
      out.write("								<img src=\"asset/image/jpg/product_img_hover.jpg\" alt=\"\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product_in4\">\r\n");
      out.write("							<p class=\"product_in4_name_product\">ngoi cao cap sieu vip pro\r\n");
      out.write("								vu tru</p>\r\n");
      out.write("							<div class=\"product_in4_bottom\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<p class=\"product_in4_price\">12,000,000₫</p>\r\n");
      out.write("									<p class=\"product_in4_sale_price\">6,000,000₫</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"product_in4_wishlist\">\r\n");
      out.write("									<i class=\"fa-solid fa-heart\"></i> <span class=\"hint_wishlist\">yêu\r\n");
      out.write("										thích</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"product_btn\">\r\n");
      out.write("							<a class=\" product_btn-add_card_none\">Thêm vào giỏ</a> <a\r\n");
      out.write("								class=\" product_btn--product_detail_none\">xem thêm</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-3 col-sm-6 col-md-4 product\">\r\n");
      out.write("						<div class=\"product_img\">\r\n");
      out.write("							<img src=\"asset/image/jpg/product_img.jpg\" alt=\"\">\r\n");
      out.write("							<div class=\"product_img_hover\">\r\n");
      out.write("								<img src=\"asset/image/jpg/product_img_hover.jpg\" alt=\"\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product_in4\">\r\n");
      out.write("							<p class=\"product_in4_name_product\">ngoi cao cap sieu vip pro\r\n");
      out.write("								vu tru</p>\r\n");
      out.write("							<div class=\"product_in4_bottom\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<p class=\"product_in4_price\">12,000,000₫</p>\r\n");
      out.write("									<p class=\"product_in4_sale_price\">6,000,000₫</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"product_in4_wishlist\">\r\n");
      out.write("									<i class=\"fa-solid fa-heart\"></i> <span class=\"hint_wishlist\">yêu\r\n");
      out.write("										thích</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"product_btn\">\r\n");
      out.write("							<a class=\" product_btn-add_card_none\">Thêm vào giỏ</a> <a\r\n");
      out.write("								class=\" product_btn--product_detail_none\">xem thêm</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-3 col-sm-6 col-md-4 product\">\r\n");
      out.write("						<div class=\"product_img\">\r\n");
      out.write("							<img src=\"asset/image/jpg/product_img.jpg\" alt=\"\">\r\n");
      out.write("							<div class=\"product_img_hover\">\r\n");
      out.write("								<img src=\"asset/image/jpg/product_img_hover.jpg\" alt=\"\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product_in4\">\r\n");
      out.write("							<p class=\"product_in4_name_product\">ngoi cao cap sieu vip pro\r\n");
      out.write("								vu tru</p>\r\n");
      out.write("							<div class=\"product_in4_bottom\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<p class=\"product_in4_price\">12,000,000₫</p>\r\n");
      out.write("									<p class=\"product_in4_sale_price\">6,000,000₫</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"product_in4_wishlist\">\r\n");
      out.write("									<i class=\"fa-solid fa-heart\"></i> <span class=\"hint_wishlist\">yêu\r\n");
      out.write("										thích</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"product_btn\">\r\n");
      out.write("							<a class=\" product_btn-add_card_none\">Thêm vào giỏ</a> <a\r\n");
      out.write("								class=\" product_btn--product_detail_none\">xem thêm</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-3 col-sm-6 col-md-4 product\">\r\n");
      out.write("						<div class=\"product_img\">\r\n");
      out.write("							<img src=\"asset/image/jpg/product_img.jpg\" alt=\"\">\r\n");
      out.write("							<div class=\"product_img_hover\">\r\n");
      out.write("								<img src=\"asset/image/jpg/product_img_hover.jpg\" alt=\"\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product_in4\">\r\n");
      out.write("							<p class=\"product_in4_name_product\">ngoi cao cap sieu vip pro\r\n");
      out.write("								vu tru</p>\r\n");
      out.write("							<div class=\"product_in4_bottom\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<p class=\"product_in4_price\">12,000,000₫</p>\r\n");
      out.write("									<p class=\"product_in4_sale_price\">6,000,000₫</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"product_in4_wishlist\">\r\n");
      out.write("									<i class=\"fa-solid fa-heart\"></i> <span class=\"hint_wishlist\">yêu\r\n");
      out.write("										thích</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"product_btn\">\r\n");
      out.write("							<a class=\" product_btn-add_card_none\">Thêm vào giỏ</a> <a\r\n");
      out.write("								class=\" product_btn--product_detail_none\">xem thêm</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"row mb-3\">\r\n");
      out.write("					<div class=\"col-lg-3 col-sm-6 col-md-4 product\">\r\n");
      out.write("						<div class=\"product_img\">\r\n");
      out.write("							<img src=\"asset/image/jpg/product_img.jpg\" alt=\"\">\r\n");
      out.write("							<div class=\"product_img_hover\">\r\n");
      out.write("								<img src=\"asset/image/jpg/product_img_hover.jpg\" alt=\"\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product_in4\">\r\n");
      out.write("							<p class=\"product_in4_name_product\">ngoi cao cap sieu vip pro\r\n");
      out.write("								vu tru</p>\r\n");
      out.write("							<div class=\"product_in4_bottom\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<p class=\"product_in4_price\">12,000,000₫</p>\r\n");
      out.write("									<p class=\"product_in4_sale_price\">6,000,000₫</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"product_in4_wishlist\">\r\n");
      out.write("									<i class=\"fa-solid fa-heart\"></i> <span class=\"hint_wishlist\">yêu\r\n");
      out.write("										thích</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"product_btn\">\r\n");
      out.write("							<a class=\" product_btn-add_card_none\">Thêm vào giỏ</a> <a\r\n");
      out.write("								class=\" product_btn--product_detail_none\">xem thêm</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-3 col-sm-6 col-md-4 product\">\r\n");
      out.write("						<div class=\"product_img\">\r\n");
      out.write("							<img src=\"asset/image/jpg/product_img.jpg\" alt=\"\">\r\n");
      out.write("							<div class=\"product_img_hover\">\r\n");
      out.write("								<img src=\"asset/image/jpg/product_img_hover.jpg\" alt=\"\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product_in4\">\r\n");
      out.write("							<p class=\"product_in4_name_product\">ngoi cao cap sieu vip pro\r\n");
      out.write("								vu tru</p>\r\n");
      out.write("							<div class=\"product_in4_bottom\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<p class=\"product_in4_price\">12,000,000₫</p>\r\n");
      out.write("									<p class=\"product_in4_sale_price\">6,000,000₫</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"product_in4_wishlist\">\r\n");
      out.write("									<i class=\"fa-solid fa-heart\"></i> <span class=\"hint_wishlist\">yêu\r\n");
      out.write("										thích</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"product_btn\">\r\n");
      out.write("							<a class=\" product_btn-add_card_none\">Thêm vào giỏ</a> <a\r\n");
      out.write("								class=\" product_btn--product_detail_none\">xem thêm</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-3 col-sm-6 col-md-4 product\">\r\n");
      out.write("						<div class=\"product_img\">\r\n");
      out.write("							<img src=\"asset/image/jpg/product_img.jpg\" alt=\"\">\r\n");
      out.write("							<div class=\"product_img_hover\">\r\n");
      out.write("								<img src=\"asset/image/jpg/product_img_hover.jpg\" alt=\"\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product_in4\">\r\n");
      out.write("							<p class=\"product_in4_name_product\">ngoi cao cap sieu vip pro\r\n");
      out.write("								vu tru</p>\r\n");
      out.write("							<div class=\"product_in4_bottom\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<p class=\"product_in4_price\">12,000,000₫</p>\r\n");
      out.write("									<p class=\"product_in4_sale_price\">6,000,000₫</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"product_in4_wishlist\">\r\n");
      out.write("									<i class=\"fa-solid fa-heart\"></i> <span class=\"hint_wishlist\">yêu\r\n");
      out.write("										thích</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"product_btn\">\r\n");
      out.write("							<a class=\" product_btn-add_card_none\">Thêm vào giỏ</a> <a\r\n");
      out.write("								class=\" product_btn--product_detail_none\">xem thêm</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-3 col-sm-6 col-md-4 product\">\r\n");
      out.write("						<div class=\"product_img\">\r\n");
      out.write("							<img src=\"asset/image/jpg/product_img.jpg\" alt=\"\">\r\n");
      out.write("							<div class=\"product_img_hover\">\r\n");
      out.write("								<img src=\"asset/image/jpg/product_img_hover.jpg\" alt=\"\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product_in4\">\r\n");
      out.write("							<p class=\"product_in4_name_product\">ngoi cao cap sieu vip pro\r\n");
      out.write("								vu tru</p>\r\n");
      out.write("							<div class=\"product_in4_bottom\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<p class=\"product_in4_price\">12,000,000₫</p>\r\n");
      out.write("									<p class=\"product_in4_sale_price\">6,000,000₫</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"product_in4_wishlist\">\r\n");
      out.write("									<i class=\"fa-solid fa-heart\"></i> <span class=\"hint_wishlist\">yêu\r\n");
      out.write("										thích</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"product_btn\">\r\n");
      out.write("							<a class=\" product_btn-add_card_none\">Thêm vào giỏ</a> <a\r\n");
      out.write("								class=\" product_btn--product_detail_none\">xem thêm</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.js\"\r\n");
      out.write("	integrity=\"sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("		$('.year').html((new Date(jQuery.now())).getFullYear())\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	/*\r\n");
      out.write("	Create: Cao Thành Named\r\n");
      out.write("	Date: 20/10/2023\r\n");
      out.write("	Note: hiện ra 2 nút thêm vào giở hàng và xem chi tiết sản phẩm\r\n");
      out.write("	 */\r\n");
      out.write("\r\n");
      out.write("	function hoverChangeProductImg() {\r\n");
      out.write("		var elementProduct = document.querySelectorAll(\".product\");\r\n");
      out.write("		var elementProductFooter = document.querySelectorAll(\".product_btn\");\r\n");
      out.write("\r\n");
      out.write("		elementProduct.forEach(function(value, index) {\r\n");
      out.write("			var elementProductBtn = value.querySelectorAll(\".product_btn a\");\r\n");
      out.write("\r\n");
      out.write("			value.onmouseover = function() {\r\n");
      out.write("				elementProductBtn[0].classList.replace(\r\n");
      out.write("						\"product_btn-add_card_none\", \"product_btn-add_card\");\r\n");
      out.write("				elementProductBtn[1].classList.replace(\r\n");
      out.write("						\"product_btn--product_detail_none\",\r\n");
      out.write("						\"product_btn--product_detail\");\r\n");
      out.write("			};\r\n");
      out.write("\r\n");
      out.write("			value.onmouseout = function() {\r\n");
      out.write("				elementProductBtn[0].classList.replace(\"product_btn-add_card\",\r\n");
      out.write("						\"product_btn-add_card_none\");\r\n");
      out.write("				elementProductBtn[1].classList.replace(\r\n");
      out.write("						\"product_btn--product_detail\",\r\n");
      out.write("						\"product_btn--product_detail_none\");\r\n");
      out.write("			};\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/*\r\n");
      out.write("	Create: Cao Thành Named\r\n");
      out.write("	Date: 19/10/2023\r\n");
      out.write("	Note: nếu ấn vào wishlist thì sản phẩm được thêm vào wishlist\r\n");
      out.write("	 */\r\n");
      out.write("\r\n");
      out.write("	function addWishList() {\r\n");
      out.write("		var elementHeartIcon = document\r\n");
      out.write("				.querySelectorAll(\".product_in4_wishlist\");\r\n");
      out.write("		elementHeartIcon.forEach(function(value) {\r\n");
      out.write("			value.onclick = function() {\r\n");
      out.write("				value.classList.toggle(\"add_wish_list\");\r\n");
      out.write("			};\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	var active = 0;\r\n");
      out.write("	var elementImgItem = document.querySelectorAll(\".slider_img_item\");\r\n");
      out.write("	var elementImgList = document.querySelector(\".slider_img_list\");\r\n");
      out.write("	var length = elementImgItem.length;\r\n");
      out.write("	var elementLeft = document.querySelector(\".left\");\r\n");
      out.write("	var elementRight = document.querySelector(\".right\");\r\n");
      out.write("\r\n");
      out.write("	var elementDot = document.querySelectorAll(\".slider_dot_item\");\r\n");
      out.write("\r\n");
      out.write("	function moveLeft() {\r\n");
      out.write("		elementLeft.onclick = function() {\r\n");
      out.write("			if (active === 0) {\r\n");
      out.write("				active = length;\r\n");
      out.write("			}\r\n");
      out.write("			active--;\r\n");
      out.write("			reloadSlider();\r\n");
      out.write("		};\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function moveRight() {\r\n");
      out.write("		elementRight.onclick = function() {\r\n");
      out.write("			if (active === length - 1) {\r\n");
      out.write("				active = -1;\r\n");
      out.write("			}\r\n");
      out.write("			active++;\r\n");
      out.write("			reloadSlider();\r\n");
      out.write("		};\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function autoSlider() {\r\n");
      out.write("		setInterval(function() {\r\n");
      out.write("			elementRight.click();\r\n");
      out.write("		}, 5000);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function reloadSlider() {\r\n");
      out.write("		var checkLeft = elementImgItem[active].offsetLeft;\r\n");
      out.write("		elementImgList.style.left = -checkLeft + \"px\";\r\n");
      out.write("\r\n");
      out.write("		var elementLastDotActive = document\r\n");
      out.write("				.querySelector('.slider_dot_item.background_dot_slider-active');\r\n");
      out.write("		elementLastDotActive.classList.remove('background_dot_slider-active');\r\n");
      out.write("		elementDot[active].classList.add('background_dot_slider-active');\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function clickDot() {\r\n");
      out.write("		elementDot.forEach(function(value, index) {\r\n");
      out.write("			value.addEventListener(\"click\", function() {\r\n");
      out.write("				active = index;\r\n");
      out.write("				reloadSlider();\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
